web1:
  build: webapp
  links:
    - mongodb1
  ports:
    - 3001:3000
  environment:
     MONGO_PORT_27017_TCP_ADDR: mongodb1
     MONGO_PORT_27017_TCP_PORT: 27001

mongodb1:
  image: mongo
#  build: mongo_image
  command: "mongod --noprealloc --smallfiles --port 27001"
#  expose:
#    - 27000
#  ports:
#    - 27000:27000
#  environment:
#     MONGO_PORT_27017_TCP_PORT: 27000
  volumes:
    - ./mongodata1:/data/db

web2:
  build: webapp
  links:
    - mongodb2
  ports:
    - 3002:3000
  environment:
     MONGO_PORT_27017_TCP_ADDR: mongodb2
     MONGO_PORT_27017_TCP_PORT: 27002

mongodb2:
  image: mongo
#  build: mongo_image
  command: "mongod --noprealloc --smallfiles --port 27002"
#  expose:
#    - 27000
#  ports:
#    - 27000:27000
#  environment:
#     MONGO_PORT_27017_TCP_PORT: 27000
  volumes:
    - ./mongodata2:/data/db

